### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by efemeryds** [Toumash/hearty#13]
All data should be ultimately stored in the linked mongodb server.

Firstly complete this task https://github.com/Toumash/hearty/issues/10

## Entites to store
 - subscriptions
 - links
 - userIds

## Proposal
NoSQL data sctucture
```
{
  "users": {
    "user-id": {
      "subscription": {}
    }
  },
  "invitations": {
    "invite-id": "user-id"
  }
}
```
Todo:
 - [ ] History of interactions

## Tasks:
 - [x] create db model
 - [ ] use database instead of in-memory cache from [here](https://github.com/Toumash/hearty/issues/10)

**Comment by Toumash** [comment]
@AlicjaDobrzeniecka what do you think about the proposal?
